Repository momo-back/momo-back, pull requests merged in 2025-01, with the labels that each got.

#38 [Feature] 카카오로그아웃 기능 구현
  src/main/java/com/momo/auth/controller/KakaoOAuthController.java
  src/main/java/com/momo/auth/dto/KakaoProfile.java
  src/main/java/com/momo/auth/dto/OAuthToken.java
  src/main/java/com/momo/auth/service/KakaoAuthService.java
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/config/JWTFilter.java
  src/main/java/com/momo/config/SecurityConfig.java
  src/main/java/com/momo/config/constants/EndpointConstants.java
  src/main/java/com/momo/config/controller/LogoutController.java
  src/main/java/com/momo/config/token/service/TokenService.java
  src/main/java/com/momo/user/dto/CustomUserDetails.java
  src/main/java/com/momo/user/entity/User.java
  src/main/java/com/momo/user/service/CustomUserDetailsService.java
  src/main/java/com/momo/user/service/UserService.java
Labels: enhancement

#39 [Feature] 모임 생성 - 위치 정보 추가
  src/main/java/com/momo/meeting/controller/MeetingController.java
  src/main/java/com/momo/meeting/dto/create/MeetingCreateRequest.java
  src/main/java/com/momo/meeting/exception/MeetingErrorResponse.java
  src/main/java/com/momo/meeting/exception/MeetingExceptionHandler.java
  src/main/java/com/momo/meeting/exception/MethodArgumentNotValidResponse.java
  src/main/java/com/momo/meeting/service/MeetingService.java
  src/main/java/com/momo/meeting/validator/MeetingValidator.java
Labels: enhancement

#45 [Feature] 모임 참여 신청 - 생성
  src/main/java/com/momo/meeting/constant/MeetingStatus.java
  src/main/java/com/momo/meeting/exception/MeetingErrorCode.java
  src/main/java/com/momo/participation/constant/ParticipationStatus.java
  src/main/java/com/momo/participation/controller/ParticipationController.java
  src/main/java/com/momo/participation/entity/Participation.java
  src/main/java/com/momo/participation/exception/ParticipationErrorCode.java
  src/main/java/com/momo/participation/exception/ParticipationErrorResponse.java
  src/main/java/com/momo/participation/exception/ParticipationException.java
  src/main/java/com/momo/participation/exception/ParticipationExceptionHandler.java
  src/main/java/com/momo/participation/repository/ParticipationRepository.java
  src/main/java/com/momo/participation/service/ParticipationService.java
  src/main/java/com/momo/participation/validation/ParticipationValidation.java
  src/test/java/com/momo/participation/service/ParticipationServiceTest.java
  src/test/java/com/momo/participation/validation/ParticipationValidationTest.java
Labels: enhancement

#43 Feature/41/카카오연동해제
  src/main/java/com/momo/auth/controller/KakaoDeleteController.java
  src/main/java/com/momo/auth/controller/KakaoLogoutController.java
Labels: enhancement

#47 [Feature] 비밀번호 재설정 기능 구현
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/EmailRequest.java
  src/main/java/com/momo/user/dto/PasswordResetRequest.java
  src/main/java/com/momo/user/service/EmailService.java
  src/main/java/com/momo/user/service/UserService.java
Labels: enhancement

#52 [feature] 카카오 연동해제 회원 정보 DB 삭제
  src/main/java/com/momo/auth/controller/KakaoDeleteController.java
Labels: enhancement

#61 [feature] 회원정보 조회
  src/main/java/com/momo/auth/service/KakaoAuthService.java
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/config/JWTFilter.java
  src/main/java/com/momo/config/SecurityConfig.java
  src/main/java/com/momo/profile/repository/ProfileRepository.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/UserInfoResponse.java
  src/main/java/com/momo/user/entity/User.java
  src/main/java/com/momo/user/service/UserService.java
Labels: enhancement

#72 [feature] 회원정보 수정 기능
  src/main/java/com/momo/profile/entity/Profile.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/UserUpdateRequest.java
  src/main/java/com/momo/user/service/UserService.java
Labels: enhancement

#82 [docs] 회원탈퇴 호출주소 병합
  src/main/java/com/momo/auth/controller/KakaoDeleteController.java
  src/main/java/com/momo/auth/service/KakaoAuthService.java
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/service/UserService.java
Labels: documentation

#93 [feature] 타인 프로필 조회 기능
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/OtherUserInfoResponse.java
  src/main/java/com/momo/user/service/UserService.java
Labels: enhancement

#103 [delete] 불필요한 의존성 제거
  src/main/java/com/momo/auth/join/service/JoinService.java
  src/main/java/com/momo/auth/security/LoginFilter.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/CustomUserDetails.java
  src/main/java/com/momo/user/service/UserService.java
Labels: documentation

#110 [refactor] 로그아웃 호출 주소 병합
  src/main/java/com/momo/auth/controller/KakaoLogoutController.java
  src/main/java/com/momo/auth/security/CustomLogoutFilter.java
  src/main/java/com/momo/user/controller/LogoutController.java
Labels: documentation

#115 [fix] RefreshToken 관련 수정
  src/main/java/com/momo/auth/join/controller/JoinController.java
  src/main/java/com/momo/auth/join/controller/VerificationController.java
  src/main/java/com/momo/auth/join/service/JoinService.java
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/config/token/entity/RefreshToken.java
  src/main/java/com/momo/config/token/repository/RefreshTokenRepository.java
  src/main/java/com/momo/user/service/EmailService.java
  src/main/java/com/momo/user/service/UserService.java
Labels: documentation

#116 [docs] 이메일 인증 반환 메세지 수정
  src/main/java/com/momo/auth/join/controller/JoinController.java
Labels: documentation

#129 [fix] 이메일 인증 코드 발송 / 비밀번호 재설정 도메인 변경
  src/main/java/com/momo/auth/join/controller/JoinController.java
  src/main/java/com/momo/auth/join/controller/VerificationController.java
  src/main/java/com/momo/auth/join/service/JoinService.java
  src/main/java/com/momo/common/exception/ErrorCode.java
  src/main/java/com/momo/user/service/EmailService.java
Labels: documentation, enhancement

#154 [fix] 회원정보 수정기능 관련 수정
  src/main/java/com/momo/image/service/ImageService.java
  src/main/java/com/momo/user/controller/UserController.java
  src/main/java/com/momo/user/dto/UserUpdateRequest.java
  src/main/java/com/momo/user/service/UserService.java
Labels: documentation
